SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `favorite_album`;
DROP TABLE IF EXISTS `favorite_artist`;
DROP TABLE IF EXISTS `favorite_song`;
DROP TABLE IF EXISTS `playlist_song`;
DROP TABLE IF EXISTS `user_song_history`;
DROP TABLE IF EXISTS `song_genre`;
DROP TABLE IF EXISTS `album`;
DROP TABLE IF EXISTS `artist`;
DROP TABLE IF EXISTS `genre`;
DROP TABLE IF EXISTS `playlist`;
DROP TABLE IF EXISTS `song`;
DROP TABLE IF EXISTS `user`;

SET FOREIGN_KEY_CHECKS = 1;
